# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 603)
        MainWindow.setStyleSheet("background-color:rgb(74, 74, 74);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(13)
        sizePolicy.setHeightForWidth(
            self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 75 36pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 0, 0);\n"
"border:2px solid grey;")
        self.label.setText("")
        self.label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)
        self.push_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_1.sizePolicy().hasHeightForWidth())
        self.push_1.setSizePolicy(sizePolicy)
        self.push_1.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_1.setObjectName("push_1")
        self.gridLayout.addWidget(self.push_1, 3, 0, 1, 1)
        self.push_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_5.sizePolicy().hasHeightForWidth())
        self.push_5.setSizePolicy(sizePolicy)
        self.push_5.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_5.setObjectName("push_5")
        self.gridLayout.addWidget(self.push_5, 4, 1, 1, 1)
        self.push_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_7.sizePolicy().hasHeightForWidth())
        self.push_7.setSizePolicy(sizePolicy)
        self.push_7.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_7.setObjectName("push_7")
        self.gridLayout.addWidget(self.push_7, 5, 0, 1, 1)
        self.push_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_2.sizePolicy().hasHeightForWidth())
        self.push_2.setSizePolicy(sizePolicy)
        self.push_2.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_2.setObjectName("push_2")
        self.gridLayout.addWidget(self.push_2, 3, 1, 1, 1)
        self.push_point = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_point.sizePolicy().hasHeightForWidth())
        self.push_point.setSizePolicy(sizePolicy)
        self.push_point.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(222, 175, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_point.setObjectName("push_point")
        self.gridLayout.addWidget(self.push_point, 6, 2, 1, 1)
        self.push_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_6.sizePolicy().hasHeightForWidth())
        self.push_6.setSizePolicy(sizePolicy)
        self.push_6.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_6.setObjectName("push_6")
        self.gridLayout.addWidget(self.push_6, 4, 2, 1, 1)
        self.push_minus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_minus.sizePolicy().hasHeightForWidth())
        self.push_minus.setSizePolicy(sizePolicy)
        self.push_minus.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(222, 175, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_minus.setObjectName("push_minus")
        self.gridLayout.addWidget(self.push_minus, 3, 3, 1, 1)
        self.push_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_3.sizePolicy().hasHeightForWidth())
        self.push_3.setSizePolicy(sizePolicy)
        self.push_3.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_3.setObjectName("push_3")
        self.gridLayout.addWidget(self.push_3, 3, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(222, 175, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 6, 3, 1, 1)
        self.push_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_9.sizePolicy().hasHeightForWidth())
        self.push_9.setSizePolicy(sizePolicy)
        self.push_9.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_9.setObjectName("push_9")
        self.gridLayout.addWidget(self.push_9, 5, 2, 1, 1)
        self.push_add = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_add.sizePolicy().hasHeightForWidth())
        self.push_add.setSizePolicy(sizePolicy)
        self.push_add.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(222, 175, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_add.setObjectName("push_add")
        self.gridLayout.addWidget(self.push_add, 2, 3, 1, 1)
        self.push_del = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_del.sizePolicy().hasHeightForWidth())
        self.push_del.setSizePolicy(sizePolicy)
        self.push_del.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_del.setObjectName("push_del")
        self.gridLayout.addWidget(self.push_del, 2, 2, 1, 1)
        self.push_div = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_div.sizePolicy().hasHeightForWidth())
        self.push_div.setSizePolicy(sizePolicy)
        self.push_div.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(222, 175, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_div.setObjectName("push_div")
        self.gridLayout.addWidget(self.push_div, 5, 3, 1, 1)
        self.push_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_4.sizePolicy().hasHeightForWidth())
        self.push_4.setSizePolicy(sizePolicy)
        self.push_4.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_4.setObjectName("push_4")
        self.gridLayout.addWidget(self.push_4, 4, 0, 1, 1)
        self.push_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_8.sizePolicy().hasHeightForWidth())
        self.push_8.setSizePolicy(sizePolicy)
        self.push_8.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_8.setObjectName("push_8")
        self.gridLayout.addWidget(self.push_8, 5, 1, 1, 1)
        self.push_mul = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_mul.sizePolicy().hasHeightForWidth())
        self.push_mul.setSizePolicy(sizePolicy)
        self.push_mul.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(222, 175, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_mul.setObjectName("push_mul")
        self.gridLayout.addWidget(self.push_mul, 4, 3, 1, 1)
        self.push_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(
            self.push_0.sizePolicy().hasHeightForWidth())
        self.push_0.setSizePolicy(sizePolicy)
        self.push_0.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}")
        self.push_0.setObjectName("push_0")
        self.gridLayout.addWidget(self.push_0, 6, 0, 1, 2)
        self.push_clear = QtWidgets.QPushButton(self.centralwidget)
        self.push_clear.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_clear.sizePolicy().hasHeightForWidth())
        self.push_clear.setSizePolicy(sizePolicy)
        self.push_clear.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(212, 224, 255);\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  color:grey;\n"
"background-color:white;\n"
"}\n"
"\n"
"")
        self.push_clear.setObjectName("push_clear")
        self.gridLayout.addWidget(self.push_clear, 1, 0, 2, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.push_1.clicked.connect(self.method_1)
        self.push_2.clicked.connect(self.method_2)
        self.push_3.clicked.connect(self.method_3)
        self.push_4.clicked.connect(self.method_4)
        self.push_5.clicked.connect(self.method_5)
        self.push_6.clicked.connect(self.method_6)
        self.push_7.clicked.connect(self.method_7)
        self.push_8.clicked.connect(self.method_8)
        self.push_9.clicked.connect(self.method_9)
        self.push_0.clicked.connect(self.method_zero)
        self.push_point.clicked.connect(self.method_point)
        self.push_add.clicked.connect(self.method_plus)
        self.push_minus.clicked.connect(self.method_minus)
        self.push_mul.clicked.connect(self.method_mul)
        self.push_div.clicked.connect(self.method_div)
        self.pushButton_15.clicked.connect(self.method_equal)
        self.push_clear.clicked.connect(self.method_clear)
        self.push_del.clicked.connect(self.method_del)

    def method_1(self):
        text = self.label.text()
        self.label.setText(text+"1")

    def method_2(self):
        text = self.label.text()
        self.label.setText(text+"2")

    def method_3(self):
        text = self.label.text()
        self.label.setText(text+"3")

    def method_4(self):
        text = self.label.text()
        self.label.setText(text+"4")

    def method_5(self):
        text = self.label.text()
        self.label.setText(text+"5")

    def method_6(self):
        text = self.label.text()
        self.label.setText(text+"6")

    def method_7(self):
        text = self.label.text()
        self.label.setText(text+"7")

    def method_8(self):
        text=self.label.text()
        self.label.setText(text+"8")
        
    def method_9(self):
        text=self.label.text()
        self.label.setText(text+"9")
        
    def method_zero(self):
        text=self.label.text()
        self.label.setText(text+"0")
        
    def method_point(self):
        text = self.label.text()
        self.label.setText(text+".")

    def method_plus(self):
        text = self.label.text()
        self.label.setText(text+"+")

    def method_minus(self):
        text = self.label.text()
        self.label.setText(text+"-")

    def method_mul(self):
        text = self.label.text()
        self.label.setText(text+"*")

    def method_div(self):
        text = self.label.text()
        self.label.setText(text+"/")
        
        
    def method_clear(self):
        self.label.setText("")
        
        
    def method_del(self):
        text = self.label.text()
        self.label.setText(text[:len(text)-1])
        
        
    def method_equal(self):
        text = self.label.text()
        
        try:
           ans=eval(text)
           self.label.setText(str(ans))
           
        except:
                self.label.setText("wrong Input")
                
        
            


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.push_1.setText(_translate("MainWindow", "1"))
        self.push_1.setShortcut(_translate("MainWindow", "1"))
        self.push_5.setText(_translate("MainWindow", "5"))
        self.push_5.setShortcut(_translate("MainWindow", "5"))
        self.push_7.setText(_translate("MainWindow", "7"))
        self.push_7.setShortcut(_translate("MainWindow", "7"))
        self.push_2.setText(_translate("MainWindow", "2"))
        self.push_2.setShortcut(_translate("MainWindow", "2"))
        self.push_point.setText(_translate("MainWindow", "."))
        self.push_point.setShortcut(_translate("MainWindow", "."))
        self.push_6.setText(_translate("MainWindow", "6"))
        self.push_6.setShortcut(_translate("MainWindow", "6"))
        self.push_minus.setText(_translate("MainWindow", "-"))
        self.push_minus.setShortcut(_translate("MainWindow", "-"))
        self.push_3.setText(_translate("MainWindow", "3"))
        self.push_3.setShortcut(_translate("MainWindow", "3"))
        self.pushButton_15.setText(_translate("MainWindow", "="))
        self.pushButton_15.setShortcut(_translate("MainWindow", "="))
        self.push_9.setText(_translate("MainWindow", "9"))
        self.push_add.setText(_translate("MainWindow", "+"))
        self.push_add.setShortcut(_translate("MainWindow", "+"))
        self.push_del.setText(_translate("MainWindow", "Del"))
        self.push_del.setShortcut(_translate("MainWindow", "Del"))
        self.push_div.setText(_translate("MainWindow", "/"))
        self.push_div.setShortcut(_translate("MainWindow", "/"))
        self.push_4.setText(_translate("MainWindow", "4"))
        self.push_4.setShortcut(_translate("MainWindow", "4"))
        self.push_8.setText(_translate("MainWindow", "8"))
        self.push_mul.setText(_translate("MainWindow", "x"))
        self.push_mul.setShortcut(_translate("MainWindow", "*"))
        self.push_0.setText(_translate("MainWindow", "0"))
        self.push_0.setShortcut(_translate("MainWindow", "0"))
        self.push_clear.setText(_translate("MainWindow", "Clear"))
        self.push_clear.setShortcut(_translate("MainWindow", "Backspace"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    window=QtWidgets.QWidget()
    window.setWindowIcon(QtGui.QIcon('claculator.png'))
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
